spring:
  # 激活开发环境，默认选择为dev
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:xjtuse_rac}?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:} # 数据库密码默认为空
  mvc:
    format:
      date: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 100MB # 单文件最大大小
      max-request-size: 100MB # 单词请求最大大小
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, file:${file-upload-path}
server:
  servlet:
    encoding:
      charset: utf-8
  port: ${SERVER_PORT:8080}

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml, classpath:/mybatis/mapper/extend/*.xml

logging:
  level:
    com.example.mybatisplusdemo.mapper: debug
file-upload-path: ./file

langchain4j:
  open-ai:
    chat-model:
      base-url: ${LANGCHAIN4J_OPENAI_BASE_URL:https://dashscope.aliyuncs.com/compatible-mode/v1}
  community:
    dashscope:
      chat-model:
        api-key: ${LANGCHAIN4J_DASHSCOPE_API_KEY} # API密钥
        model-name: ${LANGCHAIN4J_DASHSCOPE_MODEL_NAME:qwen-max} # 模型名称（默认qwen-max，可通过环境变量覆盖）