# 对于需要修改的配置项，请取消注释并更改为您自己的配置信息
spring:
  datasource:
    #DB_HOST: "localhost"  # 若本地MySQL主机不是127.0.0.1
    #DB_PORT: 3306         # 若本地MySQL端口不是3306
    #DB_NAME: "xjtuse_rac"     # 若本地数据库名不是xjtuse_rac
    #username: root  # 本地数据库用户名（覆盖基础配置的${DB_USERNAME}）
    password: 'XJTUse-RAC@2025'  # 本地数据库密码（覆盖基础配置的${DB_PASSWORD}）

#server:
#port: 8080

file-upload-path: ./file

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
  community:
    dashscope:
      chat-model:
        api-key: sk-ddea4205045847e6a9b09e20ce495f6b
        model-name: qwen-max